---
########## SSH Hardening Tasks ##########
- name: Ensure SSH Users Exist
  ansible.builtin.user:
    name: "{{ item.user }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    append: yes
  loop: "{{ ssh_users_and_keys }}"
  
- name: Add User to Sudo (RHEL)
  ansible.builtin.user:
    name: "{{ item.user }}"
    groups: sudo
    append: yes
  loop: "{{ ssh_users_and_keys }}"
  when: 
    - item.admin == "yes"
    - ansible_os_family == "RedHat"

- name: Add User to Wheel (DEB)
  ansible.builtin.user:
    name: "{{ item.user }}"
    groups: wheel
    append: yes
  loop: "{{ ssh_users_and_keys }}"
  when:
    - item.admin == "yes"
    - ansible_os_family == "Debian"

- name: Set SSH Allowed Users
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AllowUsers'
    line: 'AllowUsers {{ ssh_users_and_keys | map(attribute="user") | join(" ") }}'
    backup: yes
  loop: "{{ ssh_users_and_keys }}"
  register: sshd_config_changed

- name: Ensure SSH Directories Exist
  ansible.builtin.file:
    path: "/home/{{ item.user }}/.ssh"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: '0700'
  loop: "{{ ssh_users_and_keys }}"

- name: Deploy SSH PubKeys for SSH Users
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    state: present
    key: "{{ item.key }}"
  loop: "{{ ssh_users_and_keys }}"

- name: Disable Root SSH Login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin {{ allow_root_ssh }}'
    backup: yes
  register: sshd_config_changed

- name: Disable Empty Passwords
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitEmptyPasswords'
    line: 'PermitEmptyPasswords {{ allow_empty_passwords }}'
    backup: yes
  register: sshd_config_changed

- name: Disable Password Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication {{ allow_password_auth }}'
    backup: yes
  register: sshd_config_changed

- name: Enable Pubkey Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubKeyAuthentication'
    line: 'PubKeyAuthentication {{ allow_pubkey_auth }}'
    backup: yes
  register: sshd_config_changed

- name: Disable X11Forwarding
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?X11Forwarding'
    line: 'X11Forwarding {{ allow_x11_fwd }}'
    backup: yes
  register: sshd_config_changed

- name: Set 5 Minute Timeout
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?ClientAliveInterval'
    line: 'ClientAliveInterval {{ client_alive_dur }}'
    backup: yes
  register: sshd_config_changed

- name: Set HostBasedAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?HostbasedAuthentication'
    line: 'HostbasedAuthentication {{ allow_hostbased_auth }}'
    backup: yes
  register: sshd_config_changed

- name: Set IgnoreRhosts
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?IgnoreRhosts'
    line: 'IgnoreRhosts {{ ignore_rhosts }}'
    backup: yes
  register: sshd_config_changed

- name: Set SSH LogLevel
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?LogLevel'
    line: 'LogLevel {{ ssh_log_level }}'
    backup: yes
  register: sshd_config_changed

- name: Set MaxAuthTries
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?MaxAuthTries'
    line: 'MaxAuthTries {{ max_auth_tries }}'
    backup: yes
  register: sshd_config_changed

- name: Set MaxSessions
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?MaxSessions'
    line: 'MaxSessions {{ set_max_sessions }}'
    backup: yes
  register: sshd_config_changed

- name: Set MaxStartups
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?MaxStartups'
    line: 'MaxStartups {{ set_max_startups }}'
    backup: yes
  register: sshd_config_changed

- name: Set PrintMotd
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PrintMotd'
    line: 'PrintMotd {{ set_print_motd }}'
    backup: yes
  register: sshd_config_changed

- name: Restart SSHD With Changes (Debian)
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  when: 
    - sshd_config_changed is changed
    - ansible_os_family == "Debian"

- name: Restart SSHD With Changes (RHEL)
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  when:
    - sshd_config_changed is changed
    - ansible_os_family == "RedHat"